// THIS FILE HAS BEEN GENERATED BY GIG SO YOU MODIFY THIS CAREFULLY.
// Components to be deployed on the application (including web endpoints).
components = [
	Packages.gig.examples.guestbook.GuestbookEndpoint, 
	Packages.gig.examples.guestbook.GuestbookRepository, 
	Packages.gig.examples.guestbook.GuestbookService, 
	Packages.gig.examples.guestbook.WelcomeEndpoint, 
	Packages.gig.examples.guestbook.WelcomeRepository, 
	Packages.gig.examples.guestbook.WelcomeService, 
	Packages.org.eiichiro.gig.persistence.JPAEntityManagerComponent, 
	Packages.org.eiichiro.gig.persistence.JPAEntityManagerFactoryComponent, 
	Packages.org.eiichiro.gig.persistence.JPATransactionalInterceptor
]
